Repository OpenRailwayMap/OpenRailwayMap, pull requests merged in 2019-11, with the labels that each got.

#661 validator: permit lane tag on razed and abandoned railways
  validator/openrailwaymap.validator.mapcss
Labels: Validator

#503 add link to open the current map view in OSM editor
  INSTALL.md
  Makefile
  canvas.php
  index.php
  js/bitmap-map.js
  js/canvas-map.js
  js/mobile.js
  mobile.php
Labels: Website

#673 Remove Python 2.7 from Travis configuration
  .travis.yml
Labels: Other
