Repository OpenRailwayMap/OpenRailwayMap, pull requests merged in 2022-09, with the labels that each got.

#788 Update zh_CN
  locales/zh_CN/LC_MESSAGES/messages.po
Labels: Translations

#793 Speed limit sign questionmark
  validator/de-openrailwaymap.validator.mapcss
  validator/openrailwaymap.validator.mapcss
Labels: Validator

#737 Add Twitter-Link to Homepage (#131)
  index.php
  locales/de_DE/LC_MESSAGES/messages.po
  mobile.php
Labels: Website

#687 Change translation of "halt" in Spanish locale
  locales/es_ES/LC_MESSAGES/messages.po
Labels: Translations, Legend

#795 Update messages.po
  locales/pt_PT/LC_MESSAGES/messages.po
Labels: Translations

#792 ADD: Italian SCMT signalling in legend
  styles/signals.json
  styles/signals.mapcss
Labels: Rendering, Legend

#789 Update zh_TW
  locales/zh_TW/LC_MESSAGES/messages.po
Labels: Translations
