Repository OpenRailwayMap/OpenRailwayMap, pull requests merged in 2022-01, with the labels that each got.

#730 JOSM-Presets added missing translations
  josm-presets/de-avg-signals.xml
  josm-presets/de-signals-bostrab.xml
  josm-presets/de-signals-eso.xml
  josm-presets/de.xml
  locales/de_DE/LC_MESSAGES/messages.po
Labels: JOSM Preset

#749 Vmax5
  styles/icons/de/lf4-ds301-0-sign-down-16.png
  styles/icons/de/lf4-ds301-0-sign-down-22.png
  styles/icons/de/lf4-ds301-0-sign-down-32.png
  styles/icons/de/lf4-ds301-0-sign-down-44.png
  styles/icons/de/lf4-ds301-0-sign-down.svg
  styles/icons/de/lf4-ds301-15-sign-down-16.png
  styles/icons/de/lf4-ds301-15-sign-down-22.png
  styles/icons/de/lf4-ds301-15-sign-down-32.png
  styles/icons/de/lf4-ds301-15-sign-down-44.png
  styles/icons/de/lf4-ds301-15-sign-down.svg
  styles/icons/de/lf6-15-sign-down-16.png
  styles/icons/de/lf6-15-sign-down-22.png
  styles/icons/de/lf6-15-sign-down-32.png
  styles/icons/de/lf6-15-sign-down-44.png
  styles/icons/de/lf6-15-sign-down.svg
  styles/icons/de/lf6-5-sign-down-16.png
  styles/icons/de/lf6-5-sign-down-22.png
  styles/icons/de/lf6-5-sign-down-32.png
  styles/icons/de/lf6-5-sign-down-44.png
  styles/icons/de/lf6-5-sign-down.svg
  styles/icons/de/lf7-15-sign-16.png
  styles/icons/de/lf7-15-sign-22.png
  styles/icons/de/lf7-15-sign-32.png
  styles/icons/de/lf7-15-sign-44.png
  styles/icons/de/lf7-15-sign.svg
  styles/icons/de/lf7-5-sign-16.png
  styles/icons/de/lf7-5-sign-22.png
  styles/icons/de/lf7-5-sign-32.png
  styles/icons/de/lf7-5-sign-44.png
  styles/icons/de/lf7-5-sign.svg
  styles/maxspeed.mapcss
Labels: Rendering

#756 refresh locales
  locales/zh_CN/LC_MESSAGES/messages.po
  locales/zh_TW/LC_MESSAGES/messages.po
Labels: Translations

#748 Ts signals
  josm-presets/de-signals-eso.xml
  styles/icons/de/ts1-12.png
  styles/icons/de/ts1-22.png
  styles/icons/de/ts1-32.png
  styles/icons/de/ts1-44.png
  styles/icons/de/ts1.svg
  styles/icons/de/ts3-16.png
  styles/icons/de/ts3-22.png
  styles/icons/de/ts3-32.png
  styles/icons/de/ts3-44.png
  styles/icons/de/ts3.svg
  styles/signals.mapcss
Labels: Rendering

#761 Add josm-preset details to local operated switches according to wiki
  josm-presets/de.xml
Labels: JOSM Preset

#758 use eval expressions for speed signal icons
  styles/maxspeed.mapcss
Labels: Rendering
